version: '3.8'
services:
    php-apache:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 80:80
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: manthan
            MYSQL_DATABASE: shop_db
